--creating view Script for loan_product
/*
DEVELOPER NAME 		: CHINMAY NAIK
DEVELOPER TOPIC		: VIEW FOR LENDING APPLICATION
DEVELOPER DATE		: 25-MAR-2022
DEVELOPER TIME		: 12:49 PM
VERSION			: 1.0
*/

create view loan_product_ins_vw
as
select PROD_ID,
 PROD_TITLE,
 PROD_SUMMARY,
 INTEREST_RATE,
 MIN_LOAN_AMT,
 MAX_LOAN_AMT,
 TERM_MIN,
 TERM_MAX,
 REPAYMENT_FREQUENCY,
 REPAYMENT_AMOUNT,
 EARLY_REPAY_ALLOWED,
 MIN_AGE_LIMIT,
 MAX_AGE_LIMIT,
 RESIDENT,
 PROD_START_DT,
 PROD_END_DT
	from loan_product;